### ISSUE TITLE
입출력 빠르게 하기

### ISSUE THREAD

**Issue by tiger1710** [ps-kjj/acmicpc.net#5]
`https://www.acmicpc.net/blog/view/56` 를 참고

## C++
* C++17 `ios_base::sync_with_stdio(false);` ,  `cin.tie(NULL);`

## Java
* `BufferedReader` ,  `Integer.parseInt`

**Comment by medAndro** [comment]
## Python
* `import sys`
`list(map(int, sys.stdin.readline().split()))`
공백으로 구분된 정수를 리스트로 한번에 로드

* `import sys`
`list(map(int, sys.stdin))`
엔터로 구분된 정수를 리스트로 한번에 로드

**Comment by tiger1710** [comment]
## Rust

https://blog.kiwiyou.dev/ps/rust-ps-tips/
